openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Jobs Triggers
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  parameters:
    triggerId:
      name: triggerId
      in: path
      description: The ID of the Job Trigger on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    jobTrigger:
      description: Trigger for the Job
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntity'
        - type: object
          properties:
            startsOn:
              type: string
              format: 'date-time'
            endsOn:
              type: string
              format: 'date-time'
            triggerDefinitionId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            triggerProperties:
              type: array
              items:
                $ref: '../triggerDefinition/triggerDefinition.yaml#/components/schemas/triggerProperty'
          example:
            type: trigger
            id: OlIPEFS4MYU
            scopeId: AQ
            createdOn: '2019-12-06T11:01:16.000Z'
            createdBy: AQ
            modifiedOn: '2019-12-06T11:01:16.000Z'
            modifiedBy: AQ
            optlock: 1
            name: cron
            endsOn: '2019-12-07T01:30:00+01:00'
            startsOn: '2019-12-06T12:00:00+01:00'
            triggerDefinitionId: AQ
            triggerProperties:
              - name: cronExpression
                propertyType: java.lang.String
                propertyValue: '* 0/5 * * * ?'
              - name: jobId
                propertyType: org.eclipse.kapua.model.id.KapuaId
                propertyValue: auSoU2ph1bY
              - name: scopeId
                propertyType: org.eclipse.kapua.model.id.KapuaId
                propertyValue: AQ
    jobTriggerCreator:
      description: An object that contains the informations needed to create a Job Trigger
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntityCreator'
        - type: object
          properties:
            startsOn:
              type: string
              format: 'date-time'
            endsOn:
              type: string
              format: 'date-time'
            triggerDefinitionId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            triggerProperties:
              type: array
              items:
                $ref: '../triggerDefinition/triggerDefinition.yaml#/components/schemas/triggerProperty'
      example:
        type: triggerCreator
        name: A trigger
        startsOn: '2021-01-31T00:00:00.000Z'
        triggerDefinitionId: AQ
        triggerProperties:
          - name: cronExpression
            propertyType: java.lang.String
            propertyValue: '* * * * * ? *'
    jobTriggerListResult:
      description: List of Triggers for a Job
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/jobTrigger'
          example:
            type: triggerListResult
            limitExceeded: false
            size: 3
            items:
              - type: trigger
                id: Q5psa2kJzks
                scopeId: AQ
                createdOn: '2019-12-06T11:00:49.000Z'
                createdBy: AQ
                modifiedOn: '2019-12-06T11:00:49.000Z'
                modifiedBy: AQ
                optlock: 1
                name: interval
                startsOn: '2019-12-06T12:00:00+01:00'
                triggerDefinitionId: Ag
                triggerProperties:
                  - name: interval
                    propertyType: java.lang.Integer
                    propertyValue: '3600'
                  - name: jobId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    propertyValue: auSoU2ph1bY
                  - name: scopeId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    propertyValue: AQ
              - type: trigger
                id: OlIPEFS4MYU
                scopeId: AQ
                createdOn: '2019-12-06T11:01:16.000Z'
                createdBy: AQ
                modifiedOn: '2019-12-06T11:01:16.000Z'
                modifiedBy: AQ
                optlock: 1
                name: cron
                endsOn: '2019-12-07T01:30:00+01:00'
                startsOn: '2019-12-06T12:00:00+01:00'
                triggerDefinitionId: AQ
                triggerProperties:
                  - name: cronExpression
                    propertyType: java.lang.String
                    propertyValue: '* 0/5 * * * ?'
                  - name: jobId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    propertyValue: auSoU2ph1bY
                  - name: scopeId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    propertyValue: AQ
              - type: trigger
                id: GOQMkJEQCPg
                scopeId: AQ
                createdOn: '2019-12-06T11:01:24.000Z'
                createdBy: AQ
                modifiedOn: '2019-12-06T11:01:24.000Z'
                modifiedBy: AQ
                optlock: 1
                name: device_conn
                startsOn: '2019-12-06T12:00:00+01:00'
                triggerDefinitionId: Aw
                triggerProperties:
                  - name: jobId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    propertyValue: auSoU2ph1bY
                  - name: scopeId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    propertyValue: AQ

    triggerInvalidDatesExceptionInfo:
      description: The trigger data range is invalid
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/exceptionInfo'
        - properties:
            startsOn:
              type: string
              description: The given startsOn
              format: 'date-time'
            endsOn:
              type: string
              description: The given endsOn
              format: 'date-time'
            currentDate:
              type: string
              description: The current date
              format: 'date-time'
      example:
        type: triggerInvalidDatesExceptionInfo,
        httpErrorCode: 400,
        message: Trigger with given startsOn and endsOn will never fire according to the current date,
        kapuaErrorCode: TRIGGER_INVALID_DATES,
        startsOn: 2021-01-31T00:00:00.000Z,
        endsOn: 2023-01-31T00:00:00.000Z,
        currentDate: 2024-11-28T14:49:46.671Z
    triggerInvalidSchedulingExceptionInfo:
      description: The trigger schedule with the given data range is invalid
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/exceptionInfo'
        - properties:
            startsOn:
              type: string
              description: The given startsOn
              format: 'date-time'
            endsOn:
              type: string
              description: The given endsOn
              format: 'date-time'
            triggerDefinitionId:
              description: The given TriggerDefinition.id
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            scheduling:
              type: string
              description: The given scheduling
      example:
        type: triggerInvalidSchedulingExceptionInfo,
        httpErrorCode: 400,
        message: Trigger with given startsOn and endsOn triggerDefinitionId '1' will never fire according to the given schedule '* * * * * ? 2020',
        kapuaErrorCode: TRIGGER_INVALID_SCHEDULE,
        startsOn: 2021-01-31T00:00:00.000Z,
        endsOn: 2025-01-31T00:00:00.000Z,
        triggerDefinitionId: AQ,
        scheduling: '* * * * * ? 2020'
