openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Trigger Definitions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  parameters:
    triggerDefinitionId:
      name: triggerDefinitionId
      in: path
      description: The ID of the Trigger Definition on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    triggerProperty:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          description: The description that may contain textual information for the user on how to input this property
        propertyType:
          type: string
        propertyValue:
          type: string
      required:
        - name
        - propertyType
        - propertyValue
      example:
        name: jobId
        propertyType: org.eclipse.kapua.model.id.KapuaId
        propertyValue: AQ
    triggerDefinition:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntity'
        - type: object
          properties:
            triggerType:
              type: string
              enum:
                - TIMER
                - EVENT
            processorName:
              type: string
            triggerProperties:
              type: array
              items:
                $ref: '#/components/schemas/triggerProperty'
      example:
        type: triggerDefinition
        id: AQ
        scopeId: AQ
        createdOn: '2021-01-29T14:45:04.460Z'
        createdBy: AQ
        modifiedOn: '2021-01-29T14:45:04.460Z'
        modifiedBy: AQ
        optlock: 0
        name: Cron Job
        description: Starts the job according to the given CRON expression
        processorName: org.eclipse.kapua.service.scheduler.trigger.quartz.job.KapuaJobLauncer
        triggerProperties:
          - name: cronExpression
            propertyType: java.lang.String
            description: The cron expression that defines the schedule of executions. Check documentation for CRON syntax.
          - name: jobId
            propertyType: org.eclipse.kapua.model.id.KapuaId
            description: Identifier of the job this schedule will be applied to
          - name: scopeId
            propertyType: org.eclipse.kapua.model.id.KapuaId
            description: Identifier of the scope of the job this schedule will be applied to
        triggerType: TIMER
    triggerDefinitionListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/triggerDefinition'
          example:
            type: triggerDefinitionListResult
            limitExceeded: false
            size: 3
            items:
              - type: triggerDefinition
                id: AQ
                scopeId: AQ
                createdOn: '2021-01-29T14:45:04.460Z'
                createdBy: AQ
                modifiedOn: '2021-01-29T14:45:04.460Z'
                modifiedBy: AQ
                optlock: 0
                name: Cron Job
                description: Starts the job according to the given CRON expression
                processorName: org.eclipse.kapua.service.scheduler.trigger.quartz.job.KapuaJobLauncer
                triggerProperties:
                  - name: cronExpression
                    propertyType: java.lang.String
                    description: The cron expression that defines the schedule of executions. Check documentation for CRON syntax.
                  - name: jobId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    description: Identifier of the job this schedule will be applied to
                  - name: scopeId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    description: Identifier of the scope of the job this schedule will be applied to
                triggerType: TIMER
              - type: triggerDefinition
                id: Ag
                scopeId: AQ
                createdOn: '2021-01-29T14:45:04.614Z'
                createdBy: AQ
                modifiedOn: '2021-01-29T14:45:04.614Z'
                modifiedBy: AQ
                optlock: 0
                name: Interval Job
                description: Starts the job according to the given interval
                processorName: org.eclipse.kapua.service.scheduler.trigger.quartz.job.KapuaJobLauncer
                triggerProperties:
                  - name: interval
                    propertyType: java.lang.Integer
                    description: Fixed time between job executions in seconds
                  - name: jobId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    description: Identifier of the job this schedule will be applied to
                  - name: scopeId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    description: Identifier of the scope of the job this schedule will be applied to
                triggerType: TIMER
              - type: triggerDefinition
                id: Aw
                scopeId: AQ
                createdOn: '2021-01-29T14:45:04.781Z'
                createdBy: AQ
                modifiedOn: '2021-01-29T14:45:04.781Z'
                modifiedBy: AQ
                optlock: 0
                name: Device Connect
                description: Starts the job when the device target connects
                processorName: '???'
                triggerProperties:
                  - name: jobId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    description: Identifier of the job this schedule will be applied to
                  - name: scopeId
                    propertyType: org.eclipse.kapua.model.id.KapuaId
                    description: Identifier of the scope of the job this schedule will be applied to
                triggerType: EVENT
