openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Package
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/packages/_uninstall:
    post:
      tags:
        - Device Management - Package
      summary: Uninstall a Package
      operationId: devicePackageUninstall
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './devicePackage.yaml#/components/schemas/devicePackageUninstallRequest'
            examples:
              basic:
                summary: Basic
                description: A request with only required properties
                value:
                  name: org.eclipse.kura.demo.heater
                  version: 1.0.500
              complete:
                summary: Complete
                description: A request with all properties
                value:
                  name: org.eclipse.kura.demo.heater
                  version: 1.0.500
                  reboot: false
                  rebootDelay: 0
      responses:
        200:
          description: The corresponding Device Management Operation to track the progress of the Device Package Uninstall Request
          content:
            application/json:
              schema:
                $ref: '../deviceOperation/deviceOperation.yaml#/components/schemas/deviceOperation'
              example:
                type: deviceManagementOperation
                id: daGd5aiInCU
                scopeId: AQ
                createdOn: '2019-11-15T11:27:24.857Z'
                createdBy: AQ
                modifiedOn: '2019-11-15T11:30:01.975Z'
                modifiedBy: Ag
                optlock: 1
                action: EXECUTE
                appId: DEPLOY
                deviceId: UVjeGkGVT3A
                operationId: I-1DnL467js
                startedOn: '2019-11-15T11:27:24.842Z'
                resource: UNINSTALL
                status: RUNNING
                operationProperties:
                  - name: kapua.package.operation.id
                    propertyType: org.eclipse.kapua.commons.model.id.KapuaEid
                    propertyValue: '2588799701293395515'
                  - name: kapua.package.download.name
                    propertyType: string
                    propertyValue: heater
                  - name: kapua.package.download.version
                    propertyType: string
                    propertyValue: 1.0.500
                log: ''
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        409:
          $ref: '../openapi.yaml#/components/responses/conflictDeviceNotConnected'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
