name: 'Set Up Runner'
description: |
  Set up runner with tools required for the build
  - Setup Java 11
  - Setup Node 16
  - Install Swagger CLI
  - Add entries to /etc/hosts
runs:
  using: "composite"
  steps:
    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Setup Node 16
      uses: actions/setup-node@v4 # Installs Node and NPM
      with:
        node-version: 16

    - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
      run: 'npm install -g @apidevtools/swagger-cli'
      shell: bash

    - name: Dns look-up Docker containers needed for tests
      run: |
        echo "127.0.0.1       message-broker" | sudo tee -a /etc/hosts
        echo "127.0.0.1       job-engine"     | sudo tee -a /etc/hosts
      shell: bash