name: Security Scan
on:
  push:
    branches:
      - 'develop'
      - 'release-**'
      - 'feat-improvedGitHubActionCaching'

env:
  BUILD_OPTS: ""
  MAVEN_OPTS: "-Xmx4096m"

jobs:
  # Documentation: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html
  owasp-dependency-check:
    name: Owasp Dependency Check
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Clones Kapua repo inside the runner
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Node 16
        uses: actions/setup-node@v4 # Installs Node and NPM
        with:
          node-version: 16

      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
        shell: bash

      - name: Cache Maven repository - External dependencies # Cache of external Maven dependencies to speed up build time
        id: cache-maven-external-deps
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-maven-develop-dependencies

      - name: Run Owasp Security Scan
        run: mvn -B ${BUILD_OPTS} -DskipTests -Psecurity-scan verify