name: Security Scan
on:
  push:
    branches:
      - 'develop'

env:
  BUILD_OPTS: ""
  MAVEN_OPTS: "-Xmx4096m"

jobs:
  # Documentation: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html
  owasp-dependency-check:
    name: Owasp Dependency Check
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository # Checks out a copy of the repository on the runner
        uses: actions/checkout@v4

      - name: Set up runner
        uses: ./.github/actions/setUpRunner

      - name: Set up Maven caches
        uses: ./.github/actions/setUpMavenCaches
        with:
          kapua-artifact-cache-enabled: 'false'

      - name: Run Owasp Security Scan
        run: mvn -B ${BUILD_OPTS} -DskipTests -Psecurity-scan verify