name: Sonar Scan

on:
  push:
    branches:
      - 'develop'
      - 'release-**'
      - 'feat-improvedGitHubActionCaching'
  pull_request:
    branches:
      - 'develop'
      - 'release-**'

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository # Checks out a copy of the repository on the runner
        uses: actions/checkout@v4

      - name: Set up runner
        uses: ./.github/actions/setUpRunner

      - name: Set up Maven caches
        uses: ./.github/actions/setUpMavenCaches
        with:
          kapua-artifact-cache-enabled: 'false'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B compile -PsonarScan

